SELECT * FROM ROLES;

SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, R.ROLE_NAME
FROM USERS U
JOIN ROLES R ON U.ROLE_ID = R.ROLE_ID
LIMIT 10;

SELECT PRODUCT_NAME, PRICE, STOCK
FROM PRODUCTS
WHERE CAFE_ID = 1;

SELECT * FROM ORDERS WHERE ORDER_STATUS = 'PENDING';

SELECT P.PRODUCT_NAME, C.CATEGORY_NAME, F.CAFE_NAME
FROM PRODUCTS P
JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
JOIN CAFES F ON P.CAFE_ID = F.CAFE_ID
LIMIT 10;

SELECT E.FIRST_NAME, E.LAST_NAME, W.WORKSTATION_NAME
FROM EMPLOYEES_CAFE E
JOIN WORKSTATION W ON E.WORKSTATION_ID = W.WORKSTATION_ID
LIMIT 10;

CALL restar_stock_producto(1002, 2);

CALL aumentar_stock_producto(1002, 5);

INSERT INTO ORDERS (USER_ID, CAFE_ID, TAKEN_BY_EMPLOYEE_ID, ORDER_STATUS, TOTAL_AMOUNT)
VALUES (1, 1, 101, 'PENDING', 15000);

SELECT * FROM auditoria_orders ORDER BY fecha DESC LIMIT 1;

SELECT CAFE_ID, SUM(TOTAL_AMOUNT) AS TOTAL_VENTAS
FROM ORDERS
WHERE ORDER_STATUS = 'COMPLETED'
GROUP BY CAFE_ID;

SELECT PRODUCT_NAME, STOCK
FROM PRODUCTS
WHERE STOCK < 10;

SELECT * FROM auditoria_orders
ORDER BY fecha DESC
LIMIT 5;

SELECT DISTINCT M.METHOD_NAME
FROM PAYMENTS P
JOIN PAYMENT_METHODS M ON P.PAYMENT_METHOD_ID = M.PAYMENT_METHOD_ID;
