CREATE DATABASE UNIEATS_DB;

USE UNIEATS_DB;

CREATE TABLE ROLES(
ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
ROLE_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE USERS(
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50) NOT NULL,
SECOND_NAME VARCHAR(50) NULL,
LAST_NAME VARCHAR(50) NOT NULL,
SECOND_LAST_NAME VARCHAR(50) NOT NULL,
CC_NUMBER VARCHAR(20) NOT NULL UNIQUE,
INSTITUTIONAL_EMAIL VARCHAR(100) NOT NULL UNIQUE,
ADDRESS VARCHAR(150) NULL,
PASSWORD VARCHAR(255) NOT NULL,
ROLE_ID INT NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);
